name: shoes_repository
description: The Repo that handles shoes
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  blackfoot_flutter_lint: ^2.0.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true