name: user_repository
description: The Repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  blackfoot_flutter_lint: ^2.0.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true