name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^4.15.8
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.7.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.8
  nested: ^1.0.0
  path: ^1.9.0
  rxdart: ^0.27.7
  shoes_repository:
    path: packages/shoes_repository
  user_repository:
    path: packages/user_repository
  uuid: ^4.4.0


dev_dependencies:
  blackfoot_flutter_lint: ^2.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/