name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  font_awesome_flutter: ^10.7.0
  nested: ^1.0.0
  shoes_repository:
    path: packages/shoes_repository
  user_repository:
    path: packages/user_repository


dev_dependencies:
  blackfoot_flutter_lint: ^2.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/