name: sneakboutique
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  blackfoot_flutter_lint: ^2.0.0
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5

  image_picker: ^1.1.1
  path: ^1.9.0
  shoes_repository:
    path: packages/shoes_repository
  user_repository:
    path: packages/user_repository
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true